"""`litehorse debug share` — bundle logs + transcript + config for triage.

Writes a plain-text bundle to a secure temp file and prints the path so
the operator can attach it to an issue. **Does not** upload anywhere by
default; ``--upload paste.rs`` is reserved for an explicit, documented
opt-in (not wired in Phase 30 — the contract is "local file only").

Redacts obvious secrets (``OPENAI_API_KEY``, any ``*_SECRET`` / ``*_TOKEN``
/ ``*_KEY`` env var, ``.env`` contents) before writing.
"""
from __future__ import annotations

import re

import typer

app = typer.Typer(
    help="Debug helpers (share log+transcript+config bundle).",
    no_args_is_help=True,
)


@app.callback()
def _root() -> None:
    """Root callback so typer builds a Group."""


# ---------- pure helpers ----------

_SECRET_ENV_RE = re.compile(r"(KEY|SECRET|TOKEN|PASSWORD)$", re.IGNORECASE)
_SECRET_VALUE_MARK = "<redacted>"


def redact_env(env: dict[str, str]) -> dict[str, str]:
    """Drop values for keys that look like secrets."""
    return {
        k: (_SECRET_VALUE_MARK if _SECRET_ENV_RE.search(k) else v)
        for k, v in env.items()
    }


def _read_log_tail(n: int) -> list[str]:
    from lite_horse.cli.commands.logs import tail_lines

    return tail_lines(n=n)


def _read_config_yaml_redacted() -> str:
    """Return the raw config.yaml text with secret-looking lines scrubbed."""
    from lite_horse.cli._settings import state_dir

    p = state_dir() / "config.yaml"
    if not p.exists():
        return ""
    raw = p.read_text(encoding="utf-8")
    out: list[str] = []
    for line in raw.splitlines():
        if _SECRET_ENV_RE.search(line.split(":", 1)[0] if ":" in line else ""):
            key = line.split(":", 1)[0]
            out.append(f"{key}: {_SECRET_VALUE_MARK}")
        else:
            out.append(line)
    return "\n".join(out)


def _transcript_for(session_key: str | None) -> str:
    from lite_horse.cli.commands import sessions as sessions_cmd

    if session_key is None:
        rows = sessions_cmd.list_sessions(limit=1)
        if not rows:
            return "(no sessions)"
        session_key = rows[0]["id"]
    session = sessions_cmd.show_session(session_key)
    if session is None:
        return f"(session {session_key!r} not found)"
    lines = [f"session: {session_key}", ""]
    for msg in session.get("messages", []):
        lines.append(f"[{msg.get('role', '?')}] {msg.get('content', '')}")
    return "\n".join(lines)


def build_bundle(
    *,
    session_key: str | None = None,
    log_lines: int = 200,
) -> str:
    """Assemble the share bundle as plain text. Pure — easy to snapshot."""
    import os

    sections: list[str] = []

    sections.append("=== litehorse debug bundle ===")
    sections.append(
        "Generated by `litehorse debug share`. Redacted: "
        "api keys / secrets / tokens."
    )

    sections.append("\n--- env (LITEHORSE_*) ---")
    env_view = redact_env({k: v for k, v in os.environ.items() if k.startswith("LITEHORSE_")})
    for k in sorted(env_view):
        sections.append(f"{k}={env_view[k]}")

    sections.append("\n--- config.yaml ---")
    sections.append(_read_config_yaml_redacted() or "(no config)")

    sections.append("\n--- session transcript ---")
    sections.append(_transcript_for(session_key))

    sections.append(f"\n--- log tail (last {log_lines}) ---")
    tail = _read_log_tail(log_lines)
    sections.append("\n".join(tail) if tail else "(log empty)")

    return "\n".join(sections) + "\n"


# ---------- Typer commands ----------

@app.command("share")
def share_cmd(
    session_key: str | None = typer.Option(
        None, "--session", help="Session key; defaults to the most recent."
    ),
    log_lines: int = typer.Option(
        200, "--lines", "-n", help="Log tail depth (1-10000)."
    ),
    upload: str | None = typer.Option(
        None,
        "--upload",
        help="Upload target (not implemented — bundle stays local).",
    ),
    json_mode: bool = typer.Option(False, "--json", help="Emit NDJSON."),
) -> None:
    """Write a log+transcript+config bundle to a temp file; print its path."""
    import tempfile

    from lite_horse.cli._output import emit_error, emit_result
    from lite_horse.cli.exit_codes import ExitCode

    capped = min(max(1, int(log_lines)), 10_000)

    if upload is not None:
        emit_error(
            "--upload is not implemented; bundle written to disk only.",
            code=int(ExitCode.USAGE),
            json_mode=json_mode,
        )
        raise typer.Exit(code=int(ExitCode.USAGE))

    body = build_bundle(session_key=session_key, log_lines=capped)

    with tempfile.NamedTemporaryFile(
        mode="w",
        prefix="litehorse-share-",
        suffix=".txt",
        delete=False,
        encoding="utf-8",
    ) as f:
        f.write(body)
        path = f.name

    emit_result({"path": path} if json_mode else path, json_mode=json_mode)
